books = [ 
{
        "id": 4,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "publisher": "O'Reilly Media",
        "published_date": "2022-04-26",
        "page_count": 1012,
        "language": "English",
    },
    {
        "id": 5,
        "title": "Effective Python",
        "author": "Brett Slatkin",
        "publisher": "Addison-Wesley",
        "published_date": "2019-11-23",
        "page_count": 480,
        "language": "English",
    },
    {
        "id": 6,
        "title": "Flask Web Development",
        "author": "Miguel Grinberg",
        "publisher": "O'Reilly Media",
        "published_date": "2018-03-01",
        "page_count": 322,
        "language": "English",
    },
    {
        "id": 7,
        "title": "Architecture Patterns with Python",
        "author": "Harry Percival",
        "publisher": "O'Reilly Media",
        "published_date": "2020-03-24",
        "page_count": 296,
        "language": "English",
    },
    {
        "id": 8,
        "title": "Two Scoops of Django",
        "author": "Daniel Roy Greenfeld",
        "publisher": "Two Scoops Press",
        "published_date": "2021-06-15",
        "page_count": 548,
        "language": "English",
    },
    {
        "id": 9,
        "title": "Python Crash Course",
        "author": "Eric Matthes",
        "publisher": "No Starch Press",
        "published_date": "2019-05-03",
        "page_count": 544,
        "language": "English",
    },
    {
        "id": 10,
        "title": "Designing Data-Intensive Applications",
        "author": "Martin Kleppmann",
        "publisher": "O'Reilly Media",
        "published_date": "2017-03-16",
        "page_count": 616,
        "language": "English",
    },
    {
        "id": 11,
        "title": "Building Microservices",
        "author": "Sam Newman",
        "publisher": "O'Reilly Media",
        "published_date": "2021-08-10",
        "page_count": 610,
        "language": "English",
    },
    {
        "id": 12,
        "title": "REST API Design Rulebook",
        "author": "Mark Masse",
        "publisher": "O'Reilly Media",
        "published_date": "2011-10-26",
        "page_count": 104,
        "language": "English",
    },
    {
        "id": 13,
        "title": "Python 数据分析实战",
        "author": "Wes McKinney",
        "publisher": "人民邮电出版社",
        "published_date": "2022-09-01",
        "page_count": 458,
        "language": "Chinese",
    }]